# [Info]
site_name: Jingxuan Wang # Title
site_url: https://wang-jingxuan.github.io/
site_author: Jingxuan Wang
site_description: Jingxuan Wang

# [Navigtion]
nav:
  - Home: index.md
  - CV: CV/README.md
  - Programming:
    - Programming/README.md
    - Machine Learning:
      - Programming/MachineLearning/README.md
      - Clustering Data: Programming/MachineLearning/pytorch_logistic_regerssion/Perfume_Grouping.md
      - Logistic Regression: Programming/MachineLearning/pytorch_logistic_regerssion/pytorch_logistic_regerssion.md
      - DNN: Programming/MachineLearning/pytorch_DNN/pytorch_DNN.md
      - CNN: Programming/MachineLearning/pytorch_convolutional_neural_network(CNN).md
      - Image Classification: Programming/MachineLearning/mnist_image_classification_DNN.md
      - SVM Algorithm: Programming/MachineLearning/pytorch_SVM_algorithm.md
    - Reprint - Two Sigma Stock Market Prediction:
      - Programming/Reprint/TwoSigma_StockMarket Prediction_Reprint/README.md
      - Market EDA: Programming/Reprint/TwoSigma_StockMarket Prediction_Reprint/Two Sigma Market EDA/Two Sigma Market EDA.md
      - News EDA: Programming/Reprint/TwoSigma_StockMarket Prediction_Reprint/Two Sigma News EDA/Two Sigma News EDA.md
      - Merging and Data preprocessing: Programming/Reprint/TwoSigma_StockMarket Prediction_Reprint/Two sigma Merging and Data prepocessing.md
      - Modeling: Programming/Reprint/TwoSigma_StockMarket Prediction_Reprint/Two Sigma Modeling/Two Sigma Modeling.md
  - About Me: Me/README.md
      

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: amber # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: Switch to dark mode # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: amber
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: en # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/wang-jingxuan/wang-jingxuan.github.io # 右上角点击跳转的链接
repo_name: wang-jingxuan.github.io # 右上角的名字
## [bottom-left corner]
copyright: Jingxuan Wang # 左下角的版权声明
## [bottom-right corner]


# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
